# Name of the project.
project: "df_20210326"

# Repository path for git
repository: "https://github.com/ykshatroff/df-20210326.git"

# Where the code should be cloned into
code_dir: "/srv/df_20210326"

# Postgres container version. This container should already exist in the server
postgres_version: "12"

# Allow/Block indexing via `X-Robots-Tag` header
#
# Set to true in test servers to disable indexing.
disable_indexing: false

# Ensure ansible uses python3 interpreter
ansible_python_interpreter: /usr/bin/python3
