# Docker-compose configuration for production

version: '2.1'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-django.production
    env_file: .env
    container_name: df_20210326_django
    restart: unless-stopped
    volumes:
      - "/var/lib/docker-nginx/files/df_20210326/assets:/files/assets"
      - "/var/log/df_20210326:/var/log/df_20210326"
    # For some reason the command also has to be specified here, otherwise the entrypoint+command combination won't
    #  work.
    entrypoint: /usr/bin/wait-for-it.sh postgres:5432 -t 60 --
    command: gunicorn df_20210326.wsgi:application --workers 2 --bind :80
    networks:
      - default
      - df_20210326_nginx
      - df_20210326_postgres
    depends_on:
      - redis
    external_links:
      - postgres-12:postgres

  node:
    build:
      context: .
      dockerfile: Dockerfile-node.production
    env_file: .env
    container_name: df_20210326_node
    restart: unless-stopped
    command: yarn start
    volumes:
      - "/var/lib/docker-nginx/files/df_20210326/app/assets:/files/assets"
      - "/var/log/df_20210326:/var/log/df_20210326"
    networks:
      - default
      - df_20210326_nginx

  redis:
    image: redis:4.0.10-alpine
    restart: unless-stopped
    sysctls:
      # To allow maintaining TCP backlog setting that defaults to 511
      net.core.somaxconn: 512
    volumes:
      - "/var/lib/docker-df_20210326/redis:/data"
    networks:
      - default

# NB: These networks must be created by ansible and contain the global nginx/postgres containers.
# Keep it in sync with ansible/roles/deploy/tasks/main.yml!
networks:
  default:
    external:
      name: df_20210326_default
  df_20210326_nginx:
    external: true
  df_20210326_postgres:
    external: true
