# Generated by Django 3.1.7 on 2021-03-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_secondary_roles',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
