# Generated by Django 3.1.7 on 2021-04-06 06:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_number_of_secondary_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='database_password',
            field=models.CharField(default=accounts.models.generate_password, max_length=255),
        ),
    ]
